### ISSUE TITLE
Download key file from other location than keyserver

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintsources#108]
If I browse to a directory which includes a Release.key file, the file won't be displayed. No .key files can be chosen, for that matter.

And while the import (local) key file is good if we already have it downloaded, it would be very nice if we could also provide a URL for mintSources to download and install. For this matter, the _"Download a key..."_ feature could treat both cases:
- 8 characters for keys coming from keyserver.ubuntu.com;
- URL for keys coming from anywhere else.

**Comment by PaulXiCao** [comment]
> If I browse to a directory which includes a Release.key file, the file won't be displayed. No .key files can be chosen, for that matter.

I cannot reproduce this error as the load key window shows any file in my case.

> ...it would be very nice if we could also provide a URL for mintSources to download and install.

This in case, seems to be alot work ..

**Comment by kneekoo** [comment]
I also run Linux Mint 18.3 (64-bit, Cinnamon) with mintsources 1.7.2, and I've had this issue even before, although I only reported it recently.

However, I just found out why it "doesn't work". It works, but mintsources asks for administrative rights and after you authenticate you get to see the root user's Home and Desktop directories.

So the real problem is mintsources doesn't open the logged-in user's home directory, but root's. I hope this is an easy fix.

**Comment by icarter09** [comment]
@kneekoo are you still experiencing this issue?

**Comment by kneekoo** [comment]
Yes, this problem still exists in mintsources 1.8.8 under Linux Mint 19.2.

**Comment by xenopeek** [comment]
Thanks for submitting your feature request for the Software Sources. For more information on our workflow and feature requests, see https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
