### ISSUE TITLE
Feature request: make PPAs and additional repositories searchable

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintsources#112]
If one has a lot of PPAs and the like, being able to search them, via the mintsource's GUI, would make Mint more pleasant to use. Thanks for your time.

**Comment by xenopeek** [comment]
Can you clarify what you want to search them for? You can open PPAs in mintsources' GUI to list the installed and available packages for each.

**Comment by CottonEaster** [comment]
Xenopeek: I mean search for PPAs by _typing text in a box, as in the search box that Mint has in its settings window_ (or as in a web search engine).

**Comment by xenopeek** [comment]
Ah, I misunderstood.

You mean like the "Search all Launchpad PPAs" function in [Y PPA Manager](http://www.webupd8.org/2010/11/y-ppa-manager-easily-search-add-remove.html).

**Comment by CottonEaster** [comment]
I think so, yes - though I have not used Y PPA Manager and a glance at the page that you link is not especially informative. Yet, my meaning should be clear. I am after a box that one types in, with the result that one finds the PPA that starts with - or perhaps just contains - the string one typed. For instance, if one has one or more 'noobslab' PPAs, then typing 'noob' in the box will display that/those PPAs. The point of such a search is . . well, as I said in an earlier post.

**Comment by xenopeek** [comment]
I'm being thickheaded but one last clarification. Are you talking about PPAs you've already added to your system? Or about any PPAs on Launchpad, that you could add to your system? The latter is what Y PPA Manager does.

**Comment by CottonEaster** [comment]
>  Are you talking about PPAs you've already added to your system? Or about any PPAs on Launchpad, that you could add to your system?

The former: PPAs that are on one's system _already_. It's those I'd like to be able to search. I suppose that Mintsources would have to make it clear that such is what is being searched, and not the latter, i.e. not PPAs available on Launchpad (unless one wanted to add that functionality as well).

**Comment by JosephMcc** [comment]
Thanks for the suggestion. I'm currently working on a bit of a revamp/cleanup of the mint sources ui. This just seem a bit like overkill. The headers are already clickable to be able to sort things ascending and descending. That seems good enough in this case.

**Comment by CottonEaster** [comment]
> The headers are already clickable to be able to sort things ascending and descending. 

True. Hence, given that few will have very many PPAs, a search function will benefit only a few.  However: it _would_ benefit a few ;and it would look slick and user-focussed to have a search box in as many settings windows as possible. So: if it is not hard to implement, it would be a good feature.

Many small features that make life easier for some users will increase the likelihood that any given user finds Mint a joy to use.
