### ISSUE TITLE
Downgrade foreign packages bug

### ISSUE THREAD

**Issue by outhud** [linuxmint/mintsources#116]
Using the Downgrade foreign packages option, I can see the list of packages that can be downgraded, but when I click on next, I get a window that just says "WARNING Review the information below very carefully before validating the command".

The rest of the window is empty, I was expected to see a terminal type window with apt running.

If I run `sudo software-sources` then I see this error at this point:

```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/foreign_packages.py", line 179, in install
    terminal.feed_child("apt-get install %s\n" % " ".join(foreign_packages), -1)
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintSources_foreign_packages.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/foreign_packages.py", line 179, in install
    terminal.feed_child("apt-get install %s\n" % " ".join(foreign_packages), -1)
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)
```
This is after upgrading to Linux Mint 19.

**Comment by Pjotr123** [comment]
I can confirm this for mintsources 1.7.9 in Linux Mint 19 Tara.

Steps to reproduce, by means of the example of inxi:

1. Make sure you have the inxi version provided by the official software sources:
sudo apt-get install --reinstall inxi

2. Install the Unit193 PPA for inxi:
sudo add-apt-repository ppa:unit193/inxi

3. sudo apt-get update

4. Launch Update Manager, refresh it and install the update for inxi.

5. Software Sources - tab PPA's: disable the unit193 PPA

6. tab Maintenance: click Downgrade foreign packages

7. Mark inxi

8. Click Downgrade.

9. You should now see a popup window with a warning, that has no dialog and can only be clicked away, thus cancelling the downgrade.

**Comment by kelebek333** [comment]
Problem solved with new package from bionic proposed. You can install manually following command from proposed or wait to move main repo.

`mkdir ~/vte2.19 && cd ~/vte2.19`
`wget http://archive.ubuntu.com/ubuntu/pool/main/v/vte2.91/gir1.2-vte-2.91_0.52.2-1ubuntu1~18.04.2_amd64.deb`
`wget http://archive.ubuntu.com/ubuntu/pool/main/v/vte2.91/libvte-2.91-0_0.52.2-1ubuntu1~18.04.2_amd64.deb`
`wget http://archive.ubuntu.com/ubuntu/pool/main/v/vte2.91/libvte-2.91-common_0.52.2-1ubuntu1~18.04.2_all.deb`
`sudo dpkg -i *.deb`

**Comment by kelebek333** [comment]
Problem solved with upsteam packages.

>   * Revert the changes to revert-pcre2.patch in the previous SRU since they introduced API incompatibilies which aren't OK in an SRU (LP: #1780501).

@clefebvre  @mtwebster @outhud

**Comment by clefebvre** [comment]
Thanks @kelebek333
