### ISSUE TITLE
mintsources runs only from mintinstall (and from terminal)

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintsources#121]
`mintsources` will run from `mintupdate` but not from a desktop launcher (a launcher created via what I believe is called 'the mint menu applet'). Nor will `mintsources` run from a launcher such as Ulauncher.

I feel that this problem has been reported before, but a search of the open and closed issues on https://github.com/linuxmint/mintsources/issues/ seems not to disclose any prior report. Nor did the websearch that I did.

`mintsources` _does_ run from a terminal, after receiving authentication via a window that pops-up.

Linux Mint 19 x64 Cinnamon.

**Comment by mtwebster** [comment]
Can't reproduce this - mintsources works fine from the menu applet (at least the stock one.)

Making a launcher, either from nemo's desktop right-click menu, or from the menu editor (adding a new entry) also works:

![image](https://user-images.githubusercontent.com/262776/44117660-f28c9b1a-9fe1-11e8-99ce-6860686d98e9.png)

**Comment by CottonEaster** [comment]
It's starting working here too, via every method except Ulauncher. Odd! Thanks for your time.
