### ISSUE TITLE
Feature Request: Manage Flatpak repositories

### ISSUE THREAD

**Issue by DanielRios549** [linuxmint/mintsources#122]
At the stage we are now, with the perfect integration on mintIntall with Flatpak packages, why mintSources does not have the ability to add and remove Flaptak repositories? I think it would be a nice feature, eliminating the necessity to use the terminal before installing a Flatpak app that isn't on Flathub repository.

**Comment by xenopeek** [comment]
Thanks for contributing to mintsources. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
