### ISSUE TITLE
mirrorsfile cannot have non-ASCII characters

### ISSUE THREAD

**Issue by sinihappo** [linuxmint/mintsources#127]
If  /usr/share/mint-mirrors/linuxmint.list has non-ASCII characters, synaptics breaks at mintSources.py L935.  open() needs encoding='utf-8':

`--- /usr/lib/linuxmint/mintSources/mintSources.py-orig	2018-10-29 12:59:37.419963403 +0200
+++ /usr/lib/linuxmint/mintSources/mintSources.py	2018-10-29 13:38:24.502286965 +0200
@@ -931,7 +931,7 @@
     def read_mirror_list(self, path):
         mirror_list = []
         country_code = None
-        mirrorsfile = open(path, "r")
+        mirrorsfile = open(path, "r",encoding='utf-8')
         for line in mirrorsfile.readlines():
             line = line.strip()
             if line != "":
`

**Comment by sinihappo** [comment]
Will this demonstrate the problem enough for you to apply the patch?

`% lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
% wget http://packages.linuxmint.com/pool/main/m/mint-mirrors/mint-mirrors_1.1.8.tar.gz
% tar -xzvf mint-mirrors_1.1.8.tar.gz
% python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = open('mint-mirrors-1.1.8/usr/share/mint-mirrors/linuxmint.list','r').readlines()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4946: ordinal not in range(128)
>>> 
`

**Comment by gm10** [comment]
Yes, good call. it's the locale, I forgot about that. This reproduces it:

`LC_ALL=C sudo mintsources`

And I had indeed missed the double byte character at 4946 (Técnico Lisboa).

The same issue could occur with all other files that get opened, so this should get patched for all other instances as well, not just the immediate one you found.

Note that I'm not on the Mint team but I don't mind submitting a pull request for this unless you prefer doing it yourself, let me know.

**Comment by sinihappo** [comment]
I made the pull request for this.  Let's see what happens!

And yes, there are probably issues like this elsewhere, too.  But correct fix would require:

- Define and document encodings and other constraints for all text configuration files.
- Check the current practice with these.
- Review and fix code accordingly.

I just hope nobody thinks that setting your locale is the right solution as it is not!

**Comment by gm10** [comment]
> I just hope nobody thinks that setting your locale is the right solution as it is not!

It's a workaround, never a solution.
