### ISSUE TITLE
Please to restore, in your mintresources list, the path: http://mirrors.serverhost.com/mint/packages

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/mintsources#130]
Hello!
Please to restore, in your mintresources list from Linux Mint 19 (Cinnamon), this path: http://mirrors.serverhost.com/mint/packages. The mirrors.serverhost.ro server now works again after 2-3 months of break. In mintsources ver. 1.8.0 has disappeared from the "Main (tara)" list, http://mirrors.serverhost.ro/mint/packages. In the previous version (1.7.9) it was.
From this source, http://mirrors.serverhost.ro/mint/packages, Linux Mint packages are downloaded very quickly.
Please fix this problem.
I use Linux Mint 19.0 (Tara) Cinnamon 64-bit, in Romanian language.
Thank you for understanding.
Sorry for my bad English.
Best regards,
Dorian Baciu

**Comment by icarter09** [comment]
@DorianB2017 are you still experiencing this issue?

**Comment by xenopeek** [comment]
All above links give a "server not found" error. Closing this here. If you've created a new Linux Mint mirror or revived an old one, see https://linuxmint.com/mirrors.php for how to get your mirror listed.
