### ISSUE TITLE
No user configured proxy support due to pkexec usage

### ISSUE THREAD

**Issue by gm10** [linuxmint/mintsources#133]
Due to launching mintsources with pkexec prefix (stated purpose: benefit from key caching for subsequent mintsources launches) it has no access to the user's environment and thus cannot use user configured proxy servers (which currently is the only way that proxies can be configured via the GUI). 

We discussed this a little while ago, raising this issue as a reminder. 

My preferred solution would be to drop the initial pkexec and refactor the whole thing to only elevate privileges where needed, ideally using the polkit API.

**Comment by icarter09** [comment]
@gm10 any update on this?

**Comment by gm10** [comment]
@icarter09 well, as you know I don't contribute here anymore. My forked tools have proxy support. :)

**Comment by icarter09** [comment]
@gm10 thanks for saying something because I did not know that. :)

**Comment by gm10** [comment]
@icarter09 fair enough. I left the team back in April. I just went and closed my remaining open issues I had on linuxmint.

**Comment by icarter09** [comment]
@gm10 thanks for closing out the remaining issues. I will keep tabs on you and your work on github.
