### ISSUE TITLE
[Feature Request] Fix GPG error “NO_PUBKEY” Option for Maintaince Section

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintsources#139]
Hi,

Could You add "Fix GPG error NO_PUBKEY" capability to Maintaince Section.

Sample issues.

https://forums.linuxmint.com/viewtopic.php?t=268816
https://mintguide.org/other/440-how-to-fix-gpg-error-no_pubkey-on-linux-mint.html

Maybe can implement adapt from launchpad-getkeys or it can be used. https://github.com/sa1/launchpad-getkeys

**Comment by gm10** [comment]
How do people lose their PPA keys?

But otherwise not a bad idea, I might implement that. There are some security concerns with automatically adding keys not even identified by their full fingerprint I guess.
