### ISSUE TITLE
[Feature Request] Fix dpkg lock Issue Option for Maintaince Section

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintsources#140]
Hi,

Especially some new users can unintentionally interrupts the apt process. For this, could you add dpkg lock problem fix to Maintaince Section of Mintsources. 

Sample issues.

https://forums.linuxmint.com/viewtopic.php?t=122377
https://forums.linuxmint.com/viewtopic.php?t=263120
https://askubuntu.com/a/102084
https://itsfoss.com/could-not-get-lock-error/
https://www.linuxuprising.com/2018/07/how-to-fix-could-not-get-lock.html

**Comment by gm10** [comment]
Frankly considering the problem is usually Synaptic running in the background I'm not convinced a fix is either needed or desired. The only legitimate way I can see to run into that issue would be somehow crashing dpkg while it's running, and that should be super rare (can't say I've run into it).
