### ISSUE TITLE
apt-add-repository doesn't have --remove (or -r) option

### ISSUE THREAD

**Issue by monsta** [linuxmint/mintsources#15]
And it should, because a lot of people using Mint 15/16 think they use the original apt-add-repository tool, read the tutorials about it, try to use --remove or -r option and wonder what's wrong.

For reference: http://forums.linuxmint.com/viewtopic.php?f=90&t=153184

**Comment by queeup** [comment]
+1
Add --remove option please.

**Comment by tp0** [comment]
+1. I was pretty surprised by this sort of difference, as you sort of expect things to be 1:1 with Ubuntu.

`ppa-purge` is fine, but it is pointless if you want to remove the PPA and the package instead of downgrading to the official repos one.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintsources/commit/2e0fb0e8a448a8a913aa76b0eb9d68aa9b347cdd

**Comment by hienha** [comment]
wow, I hope so.
