### ISSUE TITLE
unusable because of mandantory proxy

### ISSUE THREAD

**Issue by oz42** [linuxmint/mintsources#170]
This is related to #133.
I tried a workaround by creating /etc/profile.d/proxy.sh with these entries:

`https_proxy=http://10.1.2.3:8080`
`http_proxy=$https_proxy`
`ftp_proxy=$https_proxy`
`HTTPS_PROXY=$https_proxy`
`HTTP_PROXY=$https_proxy`
`FTP_PROXY=$https_proxy`
`export https_proxy http_proxy ftp_proxy HTTPS_PROXY HTTP_PROXY FTP_PROXY`

But even those are ignored by mintupdate.

**Comment by xenopeek** [comment]
Related to  #191.

**Comment by xenopeek** [comment]
Related issues are closed, with no further responses from others having a proxy issue on Linux Mint 19.3. To anyone still affected by this problem, if indeed it isn't solved, please open a new issue.
