### ISSUE TITLE
Feature request: when downgrading packages, allow selection of multiple but not all items

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintsources#173]
At present, it seems one can either select packages for downgrade either by ticking each one individually or by clicking 'select all'. But what if I want to downgrade, say, 40 out of 60 packages? It seems I must select each one individually. That is not convenient. When might one wish to do such a thing, i.e. downgrade many but not all packages? When one had some out-of-band packages, installed the Mint alpha, and then want to remove the alpha (but keeping one's other out-of-band packages).

**Comment by xenopeek** [comment]
You can select all and then untick the ones you want to keep.
