### ISSUE TITLE
mintsources error: AttributeError: module 'mintcommon' has no attribute 'APT'

### ISSUE THREAD

**Issue by thegreatyellow67** [linuxmint/mintsources#174]
Hi, today I've installed a fresh Linux Mint Cinnamon 19.1, then I've added the ppa:linuxmint-daily-build-team/daily-builds to test the latest improvements. Now for me isn't possible to open mintsources. From terminal gives me an error:

Traceback (most recent call last):
File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1691, in <module>
Application().run()
File "/usr/lib/linuxmint/mintSources/mintSources.py", line 772, in __init__
self.apt = mintcommon.APT(self._main_window)
AttributeError: module 'mintcommon' has no attribute 'APT'

How can I resolve this issue?
Thanks and best regards.

**Comment by JosephMcc** [comment]
See https://github.com/linuxmint/alpha-testing/issues/1

That is where issues with the daily builds should be reported
