### ISSUE TITLE
"Select a mirror" dialog shows mirror names instead of URLs in the URL column

### ISSUE THREAD

**Issue by fsbs** [linuxmint/mintsources#176]
Issue
-------

When opening the "Select a mirror" dialog for Linux Mint mirrors ("Base") the column titled "URL" contains names instead of URLs. Mirror names are already displayed in the tooltips. So in the current state one piece of information about a mirror (name) is display twice (both in the URL column and tooltip) while another one (URL) is not displayed at all.

One situation where URLs are an essential piece of information is selecting mirrors that support **https**. Users can look them up manually in `/usr/share/mint-mirrors/linuxmint.list` but then they lose the ability to sort them by transfer speed.

Expected behavior
-----------------------

The URL column should display URLs. Names are already displayed in tooltips. Otherwise the tooltips are completely redundant and can be removed.

Possible fix
--------------

https://github.com/linuxmint/mintsources/blob/0f0b88c6b20b76b192ee38df5437c0f59984db06/usr/lib/linuxmint/mintSources/mintSources.py#L571

In the above line replace `mirror.name` with `mirror.url`.

**Comment by xenopeek** [comment]
Adding a screenshot to illustrate the snafu.

- top shows the main mirror displays mirror **names**;
- bottom shows the base mirror displays mirror **URLs**.

![image](https://user-images.githubusercontent.com/21159972/82748436-1fae4980-9da2-11ea-95b3-e49af06d0619.png)

**Comment by xenopeek** [comment]
URL is now shown in the tooltip for main mirrors. The difference between main and base mirrors is that for main mirrors there are URLs + names while for base mirrors there are only URLs.
