### ISSUE TITLE
mintsources doesn't obey Window Manager's Button layout

### ISSUE THREAD

**Issue by slavko-milanovic** [linuxmint/mintsources#177]
If title-bar buttons are moved to left side (via Window Manager settings), mintsources still have them on the right side.

Linux Mint 19.2 Xfce  (it was the same in the previous version - 19.1)

![mintsources](https://user-images.githubusercontent.com/30292158/62424341-e3ecab00-b6cd-11e9-87a6-485f7ce4023f.jpg)

**Comment by xenopeek** [comment]
Fixed with https://github.com/linuxmint/mintsources/pull/193.
