### ISSUE TITLE
Update Romanian language for mintsources

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/mintsources#178]
Please update the Romanian language for mintsources in Linux Mint 19.2, taking the update data from here https://translations.launchpad.net/linuxmint/latest/+pots/mintsources/en/+translate.
Thank you.

**Comment by DorianB2017** [comment]
I would like, however, to be implemented my translations from here: https://translations.launchpad.net/linuxmint/latest/+pots/mintsources/en/+translate, in mintsources ver. 1.8.8 for Linux Mint 19.2.
Thank you for understanding.

**Comment by xenopeek** [comment]
Thanks for improving the translations. New translations are pulled ahead of new releases.
