### ISSUE TITLE
Malformed input

### ISSUE THREAD

**Issue by Dibro89** [linuxmint/mintsources#179]
Hi, I'm trying to install Docker on Tina (https://docs.docker.com/install/linux/docker-ce/ubuntu/) and I'm unable to setup their repository using `add-apt-repository` command:

![image](https://user-images.githubusercontent.com/16293890/63199639-30999400-c087-11e9-920d-92566cb8bb97.png)

**Workaround**
Add the repo manually to `/etc/apt/sources.list`

**See also**
https://github.com/typora/typora-issues/issues/2065
https://forums.docker.com/t/59436/4
https://stackoverflow.com/q/57402923
#171

**Comment by BrHal** [comment]
Happened to me as well. The '[ option=value ]' is rejected due to an incomplete regexp, below is how I fixed /usr/lib/linuxmint/mintSources/mintSources.py

```
211c211
<     r = re.compile(r'(?:deb|deb-src)\s+\w+:/\S+?/?\s+\S+')
---
>     r = re.compile(r'(?:deb|deb-src)\s+(?:\[.*\])\s+\w+:/\S+?/?\s+\S+')

```
