### ISSUE TITLE
Stuck on error in apt-configuration

### ISSUE THREAD

**Issue by MartinX3** [linuxmint/mintsources#181]
**Describe the bug**
I can't use the "add missing keys" function of the application sources manager.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4518092/67381439-354d5d80-f58c-11e9-87a9-c5a5b014bd06.png)

**To Reproduce**
1. Open Application Sources Manager
2. Remove all software keys
3. Update the cache of the application sources (Which results in key not found errors)
4. Click on the button "add missing keys"
5. See the error "Error with your APT configuration, you may have to reload the cache first."
6. repeat the steps 3-6

**Expected behavior**
Add the missing keys

**Distribution:**
- [X] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
5.5.4.1

**Logs:**
Sadly I have no clue how to get the logs from this application.

**Comment by leigh123linux** [comment]
> **Describe the bug**
> I can't use the "add missing keys" function of the application sources manager.

>     5. See the error

The error is meaningless, can you translate it to English please?

**Comment by MartinX3** [comment]
@leigh123linux 
Of course
"Error with your APT configuration, you may have to reload the cache first."
https://github.com/linuxmint/mintsources/blob/4840ae40adb393be3dbe0ceb48f497b18709430e/usr/lib/linuxmint/mintSources/mintSources.py#L1146

**Comment by MartinX3** [comment]
After I added one key in my previously empty key list the function works again and downloaded the other keys.

**Comment by xenopeek** [comment]
Same issue as #199. @leigh123linux see my steps there to reproduce the issue.

The cause looks to be the file /etc/apt/trusted.gpg doesn't exist before user takes an action that leads to its creation.

**Comment by jmssil** [comment]
Bug is still here (Linux Mint 20 Ulyana).

Solved with:

`sudo touch /etc/apt/trusted.gpg`

**Comment by FallCheetah7373** [comment]
> Bug is still here (Linux Mint 20 Ulyana).
> 
> Solved with:
> 
> `sudo touch /etc/apt/trusted.gpg`

thanks that fixed it! I was experiencing this with 20.3 mint XFCE
