### ISSUE TITLE
Why security repository can't change to mirrors with mintsource

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintsources#182]
Hi @clefebvre ,

Why security repository can't change to mirrors with mintsource? For get security updates faster?

`deb http://security.ubuntu.com/ubuntu/ $basecodename-security main restricted universe multiverse`

**Comment by clefebvre** [comment]
I guess they could.. are they mirrored the same way?

**Comment by gm10** [comment]
To answer with a screenshot from my forked software-sources tool:
![image](https://user-images.githubusercontent.com/13855078/69955523-1f717780-14fe-11ea-895f-514e81c2f4f7.png)
