### ISSUE TITLE
Unable to add ppa when using network proxy

### ISSUE THREAD

**Issue by jesperloehr** [linuxmint/mintsources#191]
* Linux Mint 19

I only have internet access through a proxy server. Proxy is configured in network settings and in environment (http_proxy, https_proxy, no_proxy).
When trying to add a ppa either in Software Sources or with add-apt-repository the process hangs and the ppa is not added.

I believe the reason is a change in gnupg/dirmngr. When looking for a possible solution I found this Ubuntu issue: https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761
It looks like the change in dirmngr has resulted in Ubuntu no longer using dirmngr to retrieve ppa keys. 

I have solved the problem for me by forcing dirmngr to honor the proxy environment variables but this does not feel like a long term solution:
```
mv /usr/bin/dirmngr /usr/bin/dirmngr.distro
echo "\
#!/bin/bash

/usr/bin/dirmngr.distro --honor-http-proxy \$@
" > /usr/bin/dirmngr
chmod +x /usr/bin/dirmngr
```
In my opinion it would be better to change the mintsources package to not rely on dirmngr to fetch ppa keys.

**Comment by xenopeek** [comment]
I don't have a proxy but removing /usr/bin/dirmngr and then adding a PPA in mintsources doesn't add its authentication keys so indeed dirmngr is being used by mintsources.

This doesn't look to be as easy as "mintsources shouldn't rely on dirmngr" because dirmngr  is used by gnupg, which is used by apt-key, which is what [mintSources.py](https://github.com/linuxmint/mintsources/blob/master/usr/lib/linuxmint/mintSources/mintSources.py) uses:
```
def add_key_remote(key):
    try:
        subprocess.run(["apt-key", "adv", "--keyserver", "hkps://keyserver.ubuntu.com:443", "--recv-keys", key], check=True)
    except subprocess.CalledProcessError:
        return False
    return True
```

**Comment by xenopeek** [comment]
Is there anyone behind a proxy that can confirm adding PPAs through mintsources on Linux Mint 19.3 still has this issue of not adding the PPA's authentication keys?

**Comment by xenopeek** [comment]
Closing this for lack of response from others with the same problem. To anyone still affected by this problem, if indeed it isn't solved, please open a new issue.

**Comment by elschman** [comment]
see PR #209 . Should fix this
