### ISSUE TITLE
Mintsources/1.9.2 can't add repository with apt-add-repository

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintsources#196]
Hi,

Mintsources/1.9.2 can't add repository with apt-add-repository command on Linux Mint 19.3. No issue with mintsources/1.9.1 .

You can try following command for reproducing issue.

`sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' `

Output of command is below

`Malformed input, repository not added`

There is a issue only when adding a 3rd party repository. There is no issue adding PPA repository.

**Comment by xenopeek** [comment]
Thanks for reporting. Looks like that's my fault. Did a PR to fix it.

For now a workaround is to put a double space after 'deb' on the repo line:
```
sudo apt-add-repository 'deb  https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
```

**Comment by kelebek333** [comment]
@xenopeek  thanks,

I manually applied your fix and issue solved.

Best regards
