### ISSUE TITLE
unable to add repository for WineHQ

### ISSUE THREAD

**Issue by RengarBR** [linuxmint/mintsources#198]
Hello, Im new into MintLinux, I used a USB bootable Ubuntu 14.X before. I mostly do some Office stuff and Internet Browsing. Now Im trying to install Wine to play League of Legends.
The main issue is: I copy paste on Terminal the line: 

`sudo` apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'

but I get the message: (it means entry badly formulated, repository not added)
> Entrada mal formada, repositório não adicionado.
Then I got from mintforum by the user "gm10" the code:
`echo 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' | sudo tee /etc/apt/sources.list.d/wine.list`
Then I inserted code sudo apt update and got this message at the end:

> 10 packages can be upgraded. Run 'apt list --upgradable' to see them.
> N: A ignorar o ficheiro 'wine.li' no directório '/etc/apt/sources.list.d/' porque tem uma extensão inválida no nome do ficheiro
It said that it ignored the 'wine.li' at directory because it had an invalid extension on its name

This is worrying me and Idk if it will work out.
Help pls

**Comment by xenopeek** [comment]
See #196, this is a bug that's being fixed.

For now a workaround is to put a double space after 'deb' on the repo line. So for your example that would be:
```
sudo apt-add-repository 'deb  https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
```

**Comment by gm10** [comment]
> > Then I got from mintforum by the user "gm10" the code:
> > `echo 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' | sudo tee /etc/apt/sources.list.d/wine.list`
> > Then I inserted code sudo apt update and got this message at the end:
> 
> > 10 packages can be upgraded. Run 'apt list --upgradable' to see them.
> > N: A ignorar o ficheiro 'wine.li' no directório '/etc/apt/sources.list.d/' porque tem uma extensão inválida no nome do ficheiro
> > It said that it ignored the 'wine.li' at directory because it had an invalid extension on its name

For what it's worth, you did not enter the command I gave you correctly, seems you cut off the last two characters, so you ended up creating `wine.li` instead of `wine.list`.

**Comment by RengarBR** [comment]
Thank you guys for helping and being so fast on supporting us. I formated and got to install WineHQ properly, but sadly my laptop is so old that it's sandybridge core i3 doesn't support Vulkan, making it impossible for me to use Lutris on it. I installed Linux to use office and Firefox at the same time with less freezings and stuttering (didn't want to buy more laptop ddr3 RAM)

Thanks very much for helping me
