### ISSUE TITLE
Mint 20 upgraded from Mint 19: purge foreign packages will also remove essential packages

### ISSUE THREAD

**Issue by hamishmb** [linuxmint/mintsources#214]
When purging or downgrading foreign packages, the UI attempts to remove essential 
packages after upgrade from Mint 19. I then end up very carefully doing just a few at a time, and this makes the process very frustrating and slow.

Can confirm this has happened on multiple systems.

**Comment by xenopeek** [comment]
I guess it's too late to ask whether you have a list of which essential packages it were?

**Comment by hamishmb** [comment]
Unfortunately I don't think it told me which were the essential ones.

IIRC I maybe got a popup saying "these additional packages will be removed", and after saying okay (because it didn't look as though it would be a problem), it then said "error, essential packages will be removed, cannot continue" and closed itself.

Doing them a few at a time allowed me to successfully remove all the foreign packages though IIRC. It seems some old packages are still marked as essential even though they no longer exist in Mint 20?

**Comment by srshort** [comment]
I am having the same problem on 20.1, this system was set up on 19.3 and upgraded to 20 and 20.1 as they were released

I deleted everything one at a time and the problem packages seem to be
gcc-6-base 6.5.0-2ubuntu1~18.04
libnih1 1.0.3-6ubuntu2
libprocps6 2:3.3.12-3ubuntu1.2
librarian0 0.8.1-6build1
ureadahead 0.100.0-21

**Comment by hamishmb** [comment]
Thanks for fixing this. This should make the experience a lot more pleasant next time.

I won't be able to test for you, as I'm switching to LMDE, though.

Is there something to say that downgrade should be done before purge as well now?
