### ISSUE TITLE
Remove duplicate entries

### ISSUE THREAD

**Issue by jmssil** [linuxmint/mintsources#223]
When I try to Remove duplicate entries nothing happens. By launching software-sources in the terminal I see this error:

```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1133, in remove_duplicates
    with open(listfile, encoding="utf-8", errors="ignore") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/sources.list'
```

Not sure if this patch is the right way to solve this:

```
$ diff /usr/lib/linuxmint/mintSources/mintSources.py*
1131c1131
<         for listfile in glob.glob("/etc/apt/sources.list.d/*.list"):
---
>         for listfile in ["/etc/apt/sources.list"] + glob.glob("/etc/apt/sources.list.d/*.list"):

```

**Comment by xenopeek** [comment]
I've submitted a fix for the bug.

As a workaround right now I would just run `sudo touch /etc/apt/sources.list` to create the empty file and then the remove duplicates will work again.
