### ISSUE TITLE
Cancelling new mirror selection prompts to refresh APT cache

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mintsources#225]
```
Linux Mint Cinnamon 20.2
All up-to-date on 2021-07-23
```
**Issue**
I just wanted to check the list of available software sources. So, i clicked on Mirrors Main, looked at the list, but did not change anything. I just clicked the [Cancel] button. But then i got this message: **Your configuration changed - Click OK to update your APT cache.** So, just to feel totally safe, i clicked [OK] and lost a few seconds on waiting for a useless update.

**Steps to reproduce**
1. Click on Mirrors Main or Base list.
1. Take a look at the available mirrors, but don't change it, just click on [Cancel].

**Expected behaviour**
I would expect not getting this "Your configuration changed - Click OK to update your APT cache" message when i didn't change anything.

**Comment by xenopeek** [comment]
Reproducible with the steps above:

![refresh_apt](https://user-images.githubusercontent.com/21159972/126879634-f2ae99ab-c7c4-4fc8-96bd-82f76c98e5e3.gif)

**Comment by SebastJava** [comment]
**Similar and related issue**
I clicked on Mirrors Main, looked at the list, but selected the same mirror as before. Thus avoiding any changes. But then i got this message:

> Your configuration changed - Click OK to update your APT cache.

So, just to feel totally safe, i clicked [OK] and lost a few seconds on waiting for a useless update.

**Steps to reproduce**
1. Click on Mirrors Main or Base list.
2. Take a look at the available mirrors, but select the same as before.

**Expected behaviour**
I would expect not being asked for an update when i didn't change anything.

**Comment by SebastJava** [comment]
https://user-images.githubusercontent.com/31940713/126885556-7dd5222d-9549-461d-aeda-2caae1d1359d.mp4

Here i just select the same mirror as before. Just another way to cancel or "undo" any changes. I still get prompted for an APT cache update, and this is an unnecessary waste of time and resources.

**Comment by SebastJava** [comment]
Related to #218

**Comment by mtwebster** [comment]
https://github.com/linuxmint/mintsources/commit/ba608c28600aa91eea8a735dde4b11481c6e8770 merged.
