### ISSUE TITLE
Deleted authentication key reappears

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mintsources#229]
- Mint 20.2
- Cinnamon 5.0.7
- Mintsources 2.0.9 
- The only PPA I use is [Flatpak](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak?field.series_filter=focal)
---

I installed Opera [81.0.41196.54] from the deb file provided by the web. It was not what I expected so I uninstalled it from the option "Remove foreign packages." I removed the remaining Authentication Keys and updated the cache. After a couple of reboots I realized that the keys still remain. The same problem happened to me in Mint 19 when I installed GoogleEarth. 

![mintsources Opera](https://user-images.githubusercontent.com/68134588/143314065-fdf92e18-5766-4028-9a64-44acbb87f667.png)

--
When removing keys:
> h2gn@h2gn:~$ mintsources
/usr/lib/linuxmint/mintSources/mintSources.py:1564: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "parent, flags, message_type, buttons, message_format" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  d = Gtk.MessageDialog(parent,
/usr/lib/linuxmint/mintSources/mintSources.py:1564: PyGTKDeprecationWarning: The keyword(s) "message_format" have been deprecated in favor of "text" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  d = Gtk.MessageDialog(parent,
/usr/lib/linuxmint/mintSources/mintSources.py:1564: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  d = Gtk.MessageDialog(parent,
/usr/lib/linuxmint/mintSources/mintSources.py:1577: DeprecationWarning: Gtk.MessageDialog.set_image is deprecated
  d.set_image(image)
OK
/usr/lib/linuxmint/mintSources/mintSources.py:1564: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "parent, flags, message_type, buttons, message_format" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  d = Gtk.MessageDialog(parent,
/usr/lib/linuxmint/mintSources/mintSources.py:1564: PyGTKDeprecationWarning: The keyword(s) "message_format" have been deprecated in favor of "text" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  d = Gtk.MessageDialog(parent,
/usr/lib/linuxmint/mintSources/mintSources.py:1564: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  d = Gtk.MessageDialog(parent,
OK

---
[xsession-errors & logs.zip](https://github.com/linuxmint/mintsources/files/7598857/xsession-errors.logs.zip)

**Comment by xenopeek** [comment]
This is not a Software Sources problem but a Opera problem. You'll find the file `/etc/cron.daily/opera-browser` on your system and if you open it in a text editor will see it re-adds the Opera authentication keys with `apt-key` command if the keys have been removed. This file was created by the Opera installer but when your remove Opera its uninstaller leaves this file in place so it keeps adding back the Opera authentication keys every day…

You can remove the file with command:

```sudo rm -v /etc/cron.daily/opera-browser```
