### ISSUE TITLE
Can't update the cache when mintSources is launched from Synaptic

### ISSUE THREAD

**Issue by monsta** [linuxmint/mintsources#23]
Now that mintSources 1.2.6 includes /usr/bin/software-properties-gtk, it can be called from Synaptic as a repo editor. But there's an issue:
1. Install mintSources 1.2.6 (I used Mint 16 for testing).
2. Launch Synaptic as root.
3. In the menu choose Settings -> Repositories.
4. mintSources launches. Click on a button for mirror selection.
5. Press Cancel. Now "Update the cache" button is active.
6. Press "Update the cache" button.

What's expected:
Package index refresh.

What happens instead:
An error message window appears,

> Another synaptic is running.
> There is another synaptic running in interactive mode. Please close it first.

Note that you can't close Synaptic at this moment because it blocks itself from getting any input while the repo editor is running.

**Comment by monsta** [comment]
Nope, that commit doesn't fix it. You probably meant https://github.com/linuxmint/mintsources/issues/99?

**Comment by xenopeek** [comment]
Fixed with Linux Mint 19 release. The progress dialog now shows a "waiting for Synaptic to exit" message and the user closing the Synaptic window then lets the cache reload continue.
