### ISSUE TITLE
"Failed to download repository information (cdrom)" error in live mode

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mintsources#230]
![Failed-to-download-repository-info](https://user-images.githubusercontent.com/31940713/148276067-80a23b98-c7df-43bf-962b-cb73157a527e.png)

I am running a LIVE session using an USB flash stick.
I get the error message displayed in the screenshot above.

**Steps to reproduce:**

1. Go to Software Sources.
2. Change some mirrors.
3. When prompted, click OK to update the APT cache.

**Comment by SebastJava** [comment]
> Postponed towards Mint 21. We're likely to work on ubiquity and the APT backends for the next release.

https://github.com/linuxmint/mint20.3-beta/issues/42#issuecomment-1004064176

**Comment by clefebvre** [comment]
This is a known issue but it's not related to mintsources per se.
