### ISSUE TITLE
Support DEB822 format for source lists

### ISSUE THREAD

**Issue by Nihlus** [linuxmint/mintsources#236]
In 2015, apt added a new format for source lists, [DEB822](https://manpages.debian.org/unstable/apt/sources.list.5.en.html#DEB822-STYLE_FORMAT). This format is a multiline variant of the traditional one-line format, and the stated goal is to gradually make this new format the default one. If you've worked with Debian package control files, the format will be very familiar.

mintsources does not currently recognize these files and cannot be used to manage them. It'd be nice to get support for them in the program.

**Comment by Nihlus** [comment]
Having taken some time to experiment with this locally, it seems like adding support for DEB822 sources will require either a bit of a UI rework or some rather complex algorithms to separate things in the backend. 

Since the new format supports multiple suites, multiple URIs, and multiple repo types (deb & deb-src) in one paragraph (analogous to a line in the old format), disabling things on an as granular level as mintsources is capable of today gets hairly very quickly.

I have some thoughts on the matter, but I'd like some input from others first if it's even worth putting time into.

**Comment by clefebvre** [comment]
Hi @Nihlus,

Is this format widely used or recommended to users?

**Comment by Nihlus** [comment]
Yes, the intent from the Debian/dpkg side of things is to gradually make this the new standard format. The relevant quote from the linked specification is as follows:

> It is intended to make this format gradually the default format, deprecating the previously described one-line-style format, as it is easier to create, extend and modify for humans and machines alike especially if a lot of sources and/or options are involved. Developers who are working with and/or parsing apt sources are highly encouraged to add support for this format and to contact the APT team to coordinate and share this work.

**Comment by Nihlus** [comment]
Multiple well-known repos (such as Wine) have transitioned to this format as well.

**Comment by clefebvre** [comment]
Ah yes, I see it here: https://dl.winehq.org/wine-builds/debian/dists/buster/winehq-buster.sources

**Comment by clefebvre** [comment]
Ok, it definitely looks like we'll need to support this. It's only a matter of time before people follow instructions such as Wine's or some DEB actually performs the installation of such a repository via its own postinst.

Are you interested in working on this?

From a code point of view we'll probably need to abstract source files handling into a class, so that it makes no difference what the format of the file is to the rest of the code.

**Comment by Nihlus** [comment]
I can give it a go, sure - I already have some ideas on how to rework things under the hood. One of the core questions is how to handle saving of edited repos and which format they should be stored in - depending on what we choose to do, we may either need a more complex backend or end up breaking user expectations. I can type up some notes once I'm back at my computer.

**Comment by Nihlus** [comment]
Okay, so!

I'd like to iron out your (and others) view on the way mintsources should handle existing source/list files and their UI editing. Primarily, I'm wondering if we should retain information about a single repo's source format and try to preserve it, or choose a single format that mintsources always saves all changes as regardless of the original one. There are multiple considerations either way, and I'm unsure of the best approach.

## Option 1 (retain information)
This option means we have to preserve not only the source file of a repository, but also its format (line or deb822) and options. It would mean added complexity for the backend, require us to support both formats fully, and handle several edge cases related to individual configuration of various repositories that share things like URL or suite.

However, it is probably what most users would expect in terms of behaviour, since the source/list files are often user-edited or even handwritten. If mintsources simply replaced them outright, I suspect we'd have at least a couple of very surprised and unhappy users. This could probably be handled by explict confirmation dialogs and some efforts towards making it clear to the end user what is about to happen, but it's still something to consider.

## Option 2 (read anything, only write DEB822)
This option means we only need to support *reading* both formats, and whenever mintsources commits a change to disk, that change is written in the DEB822 format. Effectively, this means that while we can read traditional .list files, any change made to them via the UI would erase that file and transform it into a corresponding .sources in DEB822 format.

While this would simplify the backend and allow us far cleaner control over various options, formatting, and configuration locations, it could be quite the surprise for an unsuspecting end user. Retaining things like comments in the source files might be troublesome, and most repository sources aren't yet in DEB822 format (even though apt certainly supports it). The official .list file comes to mind, for example.

Doing it this way would offer the best futureproofing and probably the cleanest code, but will undoubtedly be a breaking change for many power users and could cause cascade effects for other programs or workflows.

## Option 3 (read anything, only write traditional format)
Same as above, but writing the traditional line format instead. This would mean any DEB822-formatted file, while supported for reading, would get written out as a .list file if edited via the UI.

Far worse futureproofing, but far better backwards compatibility. Most likely similar or equivalent code under the hood, though the list format is a little more rough to parse.

## Personal Opinions
My view is that the most reasonable option is probably 1, but I would personally prefer option 2. It'll make for better, more maintainable code and will push adoption of the DEB822 format forward. Option 1 is more conservative, but will require more work and won't always do the right thing either way.

In practice, it'll come down to customer expectations and where we want to meet them - do we want to try and interfere as little as possible with potentially handwritten files, or do we want to take an authoritative stance on the handling of repository sources? Is mintsources a complement to a user's own editing of repository sources, or should it be the primary tool in the workflow?

I'd love to hear your thoughts on this - I've started some sketchwork on option-agnostic code in my fork, but a decision on this will be instrumental going forward.

**Comment by clefebvre** [comment]
Definitely option 1 in my opinion. It's not our business to promote DEB822, only to support it.

**Comment by clefebvre** [comment]
We can use the debian.deb822 module to interact with these files.

![image](https://user-images.githubusercontent.com/1138515/194026655-060944d1-38a8-4102-9b4b-abe7f8b551be.png)

I'm not sure this supports multiple repositories defined in the same .sources file though.

**Comment by clefebvre** [comment]
If PopOS is OK with it we could also rely on repolib: https://github.com/pop-os/repolib

Moving all legacy and deb822 support towards it, we'd only deal with repolib objects, it would completely abstract the file format from mintsources.

**Comment by clefebvre** [comment]
repolib supports multiple definitions in a single file.

**Comment by clefebvre** [comment]
Sorry this took so long. I wanted to wait until we had more visibility with Mint 22.

We've got news. There's a Draft PR on repolib from @just-max, and in Mint 22 we should now have DEB822 support in python3-apt.

**Comment by clefebvre** [comment]
Python3-apt supports multiple entries in a single .sources file, but there's an issue with it.. it doesn't support [signed-by] in legacy format... this is required.

**Comment by clefebvre** [comment]
repolib works well but there are a few design features I'd like to modify:

- repolib.load_all_sources() writes to all APT sources files. Only modified files should be written to.
- comments are added in legacy format for repolib names and ident. I think we're fine with dynamically generated names and ident, especially since we don't use them in our UI.
- python3-repolib isn't just a lib, it's also a CLI and its own PPA scripts with a dbus service. These should have their own pkg imo. I'm not sure we need them here.

**Comment by clefebvre** [comment]
Implemented on master.

Thanks to @just-max for the initial PR, it helped a lot with the initial redesign.

Note: I had to remove some features from mintsources to properly handle both formats via repolib. Namely the edit buttons and the deb-src support in 3rd party repositories.

**Comment by Nihlus** [comment]
Excellent news!
