### ISSUE TITLE
Newly added PPAs explicitly reject i386 package variants

### ISSUE THREAD

**Issue by Tele42** [linuxmint/mintsources#242]
Good day,

I was pondering a couple mesa-related forum threads [1](https://forums.linuxmint.com/viewtopic.php?p=2287381) [2](https://forums.linuxmint.com/viewtopic.php?f=59&p=2286711), wondering why Linux Mint users were having trouble getting mesa updated from the oibaf and kisak-mesa PPAs. The feedback was essentially incoherent due to a lack of detail until the notes at [2#comment](https://forums.linuxmint.com/viewtopic.php?p=2287381#p2287381) got combined with a completely different forum thread [3](https://forums.linuxmint.com/viewtopic.php?f=225&p=2287375).

The user in forum thread 3 is borderline insane, smashing repo.radeon.com, ernstp-mesarc, graphics-drivers-ppa, kisak-mesa, oibaf-graphics-drivers all together and expecting anything less than a complete disaster, but that's not important for the purposes of this issue report. The detail that does matter is that newly added PPAs on Linux Mint now explicitly set arch=amd64. Some guesswork and digging later led me to stumble upon https://github.com/linuxmint/mintsources/commit/4f2722285f8c30ebb4363d52fdd8fa5b55086911#diff-5aea8a31a1cc03651e113c7be0ea8834862628ae4d53bafb13b7ad6fc5c92891R295 as the breaking change. After that commit, the Linux Mint variant of add-apt-repository will no allow apt to see i386 packages from the newly added repositories. This breaks the update process of graphics PPAs where multiarch amd64 and i386 is wanted.

I don't have the correct syntax to resolve this, but if we go back to forum thread 3, that user is also incorrectly smashing wine repos intended for bionic and kinetic in the jammy-based Linux Mint install with `deb [arch=amd64 i386] https://dl.winehq.org/wine-builds/ubuntu kinetic main` so maybe `[arch=amd64 i386]` will work as-is? EDIT: Someone mentioned that it's a comma separated list, so `[arch=amd64,i386 other=stuff]` should work and to double check the sources.list(5) man page.

In any case, this issue report is just some second-hand deduction and I haven't personally encountered this issue. Hopefully it's useful feedback.

**Comment by dpanter** [comment]
The issue still exists in April 2023. Helped another user solve the issue on their Linux Mint 21.1 gaming PC yesterday, and verified it in a fresh VM today on a fully updated system.
Added Kisak-mesa PPA, demonstrably being denied i386 packages, resulting in a broken Mesa installation on the system.
https://paste.debian.net/1276736/
