### ISSUE TITLE
Error in add-apt-repository

### ISSUE THREAD

**Issue by amitsharma928** [linuxmint/mintsources#47]
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 14, in <module>
    import pycurl
ImportError: /usr/lib/x86_64-linux-gnu/libgssapi.so.3: symbol krb5_ntlm_init_get_challange, version HEIMDAL_KRB5_2.0 not defined in file libkrb5.so.26 with link time reference

**Comment by clefebvre** [comment]
You're probably missing libkrb5-26-heimdal. Check the dependencies on your distribution, I guess python-pycurl should depend on something that depends on something that depends on that :)
