### ISSUE TITLE
Auto paste ppa clipboard when opening 'Add a new PPA' dialog

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintsources#51]
When i click the 'Add a new PPA' button in software sources, it always displays 'ppa:username/ppa', but it would be great if it checked the clipboard contents to see if the user already has it in clipboard and paste it in, so the user only has to click 'OK'.

**Comment by clefebvre** [comment]
agreed.. if the content starts with ppa:

**Comment by philipzae** [comment]
Yes if it started with ppa: and also if the url could be converted into a ppa url.

From - https://launchpad.net/~libreoffice/+archive/ubuntu/ppa
To - ppa:libreoffice/ppa
