### ISSUE TITLE
[Feature Request] Add "Select All" button to "Downgrade Foreign Packages list"

### ISSUE THREAD

**Issue by xamvolagis** [linuxmint/mintsources#59]
It would be really nice to select all packages at once in the list. Also, as of now, I'm not sure if there's any way to select the packages other than clicking on the boxes, being able to just press enter (or space) would make the process a lot faster.

Thanks

**Comment by calexil** [comment]
oh ffs please yes... it is so annoying to click 30 times over and over when testing graphics ppas...

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintsources/commit/eae224fee1bb5d4d2cf94c74a23d55bcf68585f3

**Comment by calexil** [comment]
Excellent, thanks @clefebvre !! Looking forward  to the release
