### ISSUE TITLE
Extremely wide window on Russian locale

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintsources#60]
![_2015-08-09_14-35-16](https://cloud.githubusercontent.com/assets/7345761/9154653/054a4754-3ea4-11e5-9653-3f33118e0ce1.png)
Solution is to make buttons different sizes (Independent size)
Another solution - two lined buttons (if it is possible)

**Comment by Yanpas** [comment]
Design suggestion (GIMP). Buttons should be over text (if the name of ppa is too long, window won't get wide again) Column width should be resizable
![_2015-08-09_14-35-16](https://cloud.githubusercontent.com/assets/7345761/9154710/b6a80d68-3ea6-11e5-84c9-1112fa2c770a.png)

**Comment by clefebvre** [comment]
Fixed.
