### ISSUE TITLE
Unable to enable additional repos that have the same name

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintsources#63]
I have two entries in the additional repos tab for the opera browser and i'm unable to enable them through mint sources, as they get disabled once i close the dialog. I also have two entries for google, but it doesnt have the same problem.

![screenshot-software sources](https://cloud.githubusercontent.com/assets/4412114/11376274/35d5e550-92f9-11e5-9e6a-846b280e0503.png)

**Comment by xenopeek** [comment]
Retesting with opera-beta and opera-developer on Linux Mint 18.3 this appears to have been fixed, if the root cause was in mintsources at the time.
