### ISSUE TITLE
Mirror Search Warning is Not Dismissable

### ISSUE THREAD

**Issue by MichaelTunnell** [linuxmint/mintsources#64]
The warning that tells people to scan for faster mirrors is not dismissable. If you click the OK button it just takes you to the scan but oddly enough the linuxmint.com mirror is the fastest for me as the main mirror but leaving it there is not an option because the warning doesn't have the ability to be dismissed.

I chose a different mirror just so the warning would go away.

**Comment by JosephMcc** [comment]
It can be disabled in Edit->Preferences on the "Options" tab.
