### ISSUE TITLE
Purge residual configuration doesn't warn you

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintsources#67]
Purge residual configuration doesn't warn you what it is going to do (and I still don't know what does it do (maybe purgeus config files of packages, which were installed before?)) and doesn't ask you "Are you sure you want to do this: ..."

**Comment by rzfang** [comment]
I clicked the button, then it shows as down, and never up, I even don't know what is it doing, and how long it will take...

**Comment by xenopeek** [comment]
Purge residual configuration removes any (system) configuration files in /etc from packages that are no longer installed on your system. Once the action completes a dialog pops up with "There is no more residual configuration on the system."
