### ISSUE TITLE
No way to enable ubuntu backports

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintsources#70]
The tick backports only provides backports for linux mint packages. But this doesn't enable backports from ubuntu repos.
I'm talking about these two repos:

```
deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse
```

**Comment by luca-s** [comment]
I noticed the same. I don't understand why the ubuntu backports are not enabled together with linux mint ones

**Comment by clefebvre** [comment]
That's not what the checkbox was for. I understand this was confusing though, and in Mint 18.x onwards this is now removed and this component is enabled by default and mandatory.
