### ISSUE TITLE
PPAs can't be opened using the mintsources gui in Mint 18

### ISSUE THREAD

**Issue by brownsr** [linuxmint/mintsources#77]
Once loaded PPAs can't be opened using the sources gui.  .xsession-errors seems to be indicating that the -u parameter (to lsb_release, presumably) is not being understood.  Adding something manually from the ppa via apt works just fine.

**Comment by skini151** [comment]
I started working on it, ASAP.

**Comment by brownsr** [comment]
corrected by today's commit from Clem
