### ISSUE TITLE
Software Sources window does not maximise

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintsources#82]
hat the window does not maximise - has no maximise button - is an irritation, if I may say so. It get in the way of getting things done, sometimes.

![image](https://cloud.githubusercontent.com/assets/9998846/21455740/b7a20cdc-c91a-11e6-8c22-82a65d1c228d.png)

The screenshot shows a non-standard theme. But the problem occurs with the standard themes too.

**Comment by xenopeek** [comment]
Retesting on 18.3 this appears to have been fixed at some point after this issue was reported.
