### ISSUE TITLE
Double-click on a candidate mirror should be same as clicking Apply

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintsources#86]
In the Software Sources app, the default first screen ("Official repositories") has buttons in the middle, showing Main and Base repos.  Clicking one of these opens a window titled "Select a mirror," which mostly contains a listview.  The "Select a mirror" window has an Apply button at the bottom.  

Feature request:  Double-clicking one of the "Select a mirror" list entries should be the same as single-clicking that entry & then clicking Apply.  Currently, the double-click is only equivalent to a single-click.  

LMDE 2 Betsy.  "mintsources" APT package version 1.6.3.

**Comment by xenopeek** [comment]
Retesting on Linux Mint 18.3, this appears to have been implemented. If it currently doesn't work like that yet on LMDE 2, it will on LMDE 3.
