### ISSUE TITLE
Titlebar uses nonexistent icon

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintsources#88]
I'm using one of the color variations of the Mint-X icon theme.  The title bar of the Mint "software-sources" window has a red circle-slash icon meaning "icon not found," although the global apps menu and the window-list applet in the Panel have a suitable icon for this app.  

LMDE 2 Betsy.  "mintsources" APT package version 1.6.3.

**Comment by NikoKrause** [comment]
Screenshot?
