### ISSUE TITLE
add-apt-repository --help requires sudo

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintsources#90]
mintsources 1.6.4

It seems surprising to me that I have to run add-apt-repository as root in order to obtain command line help i.e. sudo add-apt-repository --help rather than add-apt-repository --help. Shouldn't sudo only be required for root-level write/modify?

**Comment by monsta** [comment]
Same as https://github.com/linuxmint/mintsources/issues/18, fixed in 1.6.5
