### ISSUE TITLE
KDE icon is hardcoded

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/mintsources#91]
GNOME: [`Icon=mintsources`](https://github.com/linuxmint/mintsources/blob/master/usr/share/applications/mintsources.desktop#L143)

KDE: [`Icon=/usr/share/icons/hicolor/scalable/apps/software-sources.svg`](https://github.com/linuxmint/mintsources/blob/master/usr/share/applications/kde4/mintsources.desktop#L209)

**Comment by monsta** [comment]
Ok, this is now fixed in https://github.com/linuxmint/mintsources/commit/d1e506fc36776848b8704eb7572b89ccc3fd3ca3 + https://github.com/linuxmint/mintsources/commit/b97b798f675fef729104536005a8abddddf054fc.
