### ISSUE TITLE
"Reload cache" is successful even if it encountered errors 

### ISSUE THREAD

**Issue by NZamp** [linuxmint/mintsources#96]
[Using Linux Mint 18.1]
During a package installation in a terminal window, I changed the repos mirrors (from mintUpdate->Edit- Software Sources) to faster ones. After selecting the appropriate mirrors, mintSources notified me to reload the cache (upper right button), I did it, and it (obviously) ended up with an error because the other apt process was running at the same time. However, the button state changed to "No action needed" and it was grayed out, even though the cache couldn't be updated. The button should be grayed out after the cache was _successfully_ reloaded, not right after it was pressed.

_Probably it could also happen with a less obvious situation (ex. if the mirrors could not be accessed at that time), but I haven't tested it._

Just a (...way too) minor issue, as the cache would be anyway reloaded automatically at the next time mintUpdate will be checking for updates.

_Originally posted as a mintUpdate issue by mistake [closed]._

**Comment by NZamp** [comment]
@clefebvre Feature Request

**Comment by xenopeek** [comment]
This isn't trivial to implement. The code disables the button after it is clicked, before the synaptic command is run to update the cache: https://github.com/linuxmint/mintsources/blob/ca27ac69d1f1195ab5a68fb0bd4e84388bfbe60b/usr/lib/linuxmint/mintSources/mintSources.py#L1422

That's done to avoid users clicking the button twice. I don't see a reliable way to decide whether synaptic succeeded completely, partially or failed. For example the command's exit code is 0 (zero) whether all indexes could be updated, all failed (like with network disconnected) or some could be updated and some failed. What situation should re-enable the button? I think only the user can decide on this (certainly with partial success & partial failure) after reading and interpreting any error message from synaptic.

**Comment by NZamp** [comment]
Hmm... So, there isn't a way to determine if apt (or synaptic) has successfully finished the update and not just the command itself?

**Comment by PaulXiCao** [comment]
I found [https://tracker.debian.org/pkg/python-apt](python-apt) package which could (should?!) be used for most of the calls done in mintsources. 

It would also be the solution to the current issue as the included "cache refresh" method returns a boolean to determine the result.

**Comment by xenopeek** [comment]
Fixed in Linux Mint 19 release. Updating cache now shows a "waiting for apt to exit" on its progress dialog if another apt process is running.
