### ISSUE TITLE
UnicodeDecodeError at lauch with russian locale

### ISSUE THREAD

**Issue by Chocobo-ts** [linuxmint/mintsources#99]
Hi, i'm got a error in mintsources 1.6.9 (sylvia) with russian locale 
`chocobo@desktop ~ $ mintsources 
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1571, in <module>
    Application().run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 740, in __init__
    self.set_button_text(self.builder.get_object("label_ppa_add"), _("Add a new PPA..."))
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 948, in set_button_text
    encoded = text.encode('utf-8')[:BUTTON_LABEL_MAX_LENGTH] + ".."
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`

**Comment by J0Ar** [comment]
Same error but in german language...

> jarci@home ~ $ mintsources
> Traceback (most recent call last):
>   File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1571, in <module>
>     Application().run()
>   File "/usr/lib/linuxmint/mintSources/mintSources.py", line 746, in __init__
>     self.set_button_text(self.builder.get_object("label_repository_add"), _("Add a new repository..."))
>   File "/usr/lib/linuxmint/mintSources/mintSources.py", line 948, in set_button_text
>     encoded = text.encode('utf-8')[:BUTTON_LABEL_MAX_LENGTH] + ".."
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 23: ordinal not in range(128)
> jarci@home ~ $

**Comment by clefebvre** [comment]
Fixed in 1.7.0.
